version: '2'
services:
    db:
      image: mariadb:10
      container_name: mariadb
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=jobConvos
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      volumes:
        - ./mySQLBackup:/mySQLBackup
      ports:
        - "3307:3306"